### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by vbhayden** [yetanalytics/dave#165]
Morning team,

When going through the Readme stesp for setting up a development instance, I'm getting an exception after it validates the Figwheel main and starts compiling:

```
[Figwheel] Validating figwheel-main.edn
[Figwheel] figwheel-main.edn is valid \(ツ)/
[Figwheel] Compiling build dev to "target/public/cljs-out/dev-main.js"
[Figwheel] Failed to compile build dev in 0.648 seconds.
[Figwheel:WARNING] Compile Exception: error=2, No such file or directory  
[Figwheel:SEVERE] java.io.IOException: error=2, No such file or directory
```

It's not much more verbose than that, though.

edit: Clarifying:
- Ubuntu 16.04 LTS
- Browser page does try and load, but is blank ofc
- OpenJDK 1.8 and Clojure 1.10.1.536

Thanks,
-Trey

**Comment by milt** [comment]
Hey Trey,
Thanks for the environment info, I'll try to reproduce and see what's going on!
Milt

**Comment by milt** [comment]
Trey,
@cliffcaseyyet points out that we've omitted a dev dependency in the documentation, which is Node (I have it working from v8+). Make sure you have that installed and try again.
Milt

**Comment by vbhayden** [comment]
Yep, that was it.  Thanks team!

**Comment by milt** [comment]
👍
