### ISSUE TITLE
xAPI "Endpoint" Clarification / Assumption

### ISSUE THREAD

**Issue by vbhayden** [yetanalytics/dave#167]
Morning team,

The Node guidance yesterday has helped get things running, so thanks for that.

When declaring an LRS in the production setup, the `LRS Endpoint` field felt a little awkward as it's expecting the endpoint to have an `/xapi` convention.  I checked the spec awhile back and it (surprisingly) didn't actually stipulate that convention as far as I could tell -- it's just sort of popular with LRS vendors.

On a related note, it also works a bit differently than what `Endpoint` has typically meant for an LRS (also just by community convention) as it expects the pre-"xapi" subset of the URL.  As the conformance suite and xAPI wrappers typically take `Endpoint` as "something I can append `/statements` to", it might warrant a bit of clarification on what's expected in that field.  

Looking at the network tab cleared this up pretty quickly, but the 404 response toasts were an initial surprise.  You can probably just have the toast display which endpoint it tried to hit and assume that the person entering information will recognize the proper format, but it would still be problematic for an LRS whose xAPI root was just the actual root domain.

Thanks,
-Trey

**Comment by cliffcaseyyet** [comment]
Hi Trey,

Coincidentally this was actually a conversation internally today and we will be doing a fix for this exact thing in an upcoming iteration (allow the user to specify everything before "/statements" and relying on explicit spec after that). I'll update you with the PR when it's moving through.

Thanks,
Cliff

**Comment by vbhayden** [comment]
Oh cool news, thanks guys.
